# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-20.10"
  
  # Provision
  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime", run: "always"

  config.vm.network "public_network", ip: "192.168.0.13"

config.vm.define 'server' do |machine|
machine.vm.hostname = 'SRVINFRA01'
end
  # Shared folder
  config.vm.synced_folder "project/", "/home/project", create: true

end