# -*- mode: ruby -*-
# vi: set ft=ruby sw=2 st=2 et :
Vagrant.configure('2') do |config|

    config.vm.box = 'debian/buster64'
    
    # config.vm.box = "puppetlabs/debian-7.8-64-puppet"
    config.vm.box_check_update = false

    config.vm.network 'forwarded_port',
    guest: 8081,
    host: 5012,
    host_ip: 'localhost'
    config.vm.network 'public_network',ip: '192.168.0.12'

    # Mettre en place un cache pour APT
    config.vm.define 'nexus' do |machine|

        machine.vm.hostname = 'nexus'

        # Limiter la RAM de la VM Vanessa David Avril 2021
        machine.vm.provider 'virtualbox' do |vb|
            vb.memory = '3000'
        end
    end
    config.vm.synced_folder "vagrant-rsync/", "/home/rsync", create: true
end